import type { BrowserTab } from "../lib/useBrowserPanel";
import type { BalanceInfo, ContextInfo, EffortInfo, Mode, WireUsage } from "../lib/types";
import type { Todo } from "../lib/tools";
import type { RightDockTab } from "./Topbar";
import type { CodeReviewState } from "./CodeReviewSection";
import type { ReviewMode, ReviewScope } from "../lib/codeReview";

export interface RightDockProps {
  open: boolean;
  background?: boolean;
  closing?: boolean;
  tab: RightDockTab;
  onTabChange: (tab: RightDockTab) => void;
  onClose: () => void;
  tabId?: string;
  context: ContextInfo;
  usage?: WireUsage;
  sessionCost?: number;
  sessionCurrency?: string;
  scopeLabel?: string;
  refreshKey?: number;
  modelLabel?: string;
  mode?: Mode;
  effort?: EffortInfo;
  balance?: BalanceInfo;
  running?: boolean;
  cwd?: string;
  onAddToChat?: (text: string) => void;
  filePreviewPath?: string | null;
  onOpenFile?: (path: string, dockTab?: RightDockTab) => void;
  todos?: Todo[];
  todoStale?: boolean;
  onDismissTodos?: () => void;
  onStartPlan?: () => void;
  onSyncTodoProgress?: () => void;
  todoSyncing?: boolean;
  codeReview?: CodeReviewState;
  onRunCodeReview?: (mode: ReviewMode, scope: ReviewScope, paths: string[]) => void;
  onClearCodeReview?: () => void;
  browserExpanded?: boolean;
  onToggleBrowserExpanded?: () => void;
  browserTabs?: BrowserTab[];
  activeBrowserTabId?: string | null;
  onBrowserTabChange?: (id: string) => void;
  onCloseBrowserTab?: (id: string) => void;
  onNewBrowserTab?: () => void;
  onBrowserTabUrlChange?: (id: string, url: string, title?: string) => void;
  pagePreviewPath?: string | null;
  onPagePreviewPathChange?: (path: string) => void;
  onPreviewPage?: (path: string) => void;
}
